/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.smartstart.controllers;

import com.smartstart.entities.Application;
import com.smartstart.entities.Opportunity;
import com.smartstart.entities.UserSession;
import com.smartstart.entities.fos_user;
import com.smartstart.services.ApplicationService;
import com.smartstart.services.ContractServiceImpl;
import com.smartstart.services.OpportunityService;
import com.sun.glass.events.MouseEvent;
import java.io.IOException;
import java.net.URL;
import java.sql.SQLException;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.beans.binding.Bindings;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Alert;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.ListView;
import javafx.stage.Stage;

/**
 * FXML Controller class
 *
 * @author acmou
 */
public class ListApplicationForEntreprise implements Initializable {

    @FXML
    private ListView<Application> list;
    private ObservableList<Application> data = FXCollections.observableArrayList();
    @FXML
    private Button CancelButton;
    @FXML
    private Button DenyApp;
    @FXML
    private Button Accept;
    @FXML
    private Label type;
    fos_user u=new fos_user();
    OpportunityService p1 = new OpportunityService();
    ApplicationService as = new ApplicationService();
    OpportunityService os = new OpportunityService();

    /**
     * Initializes the controller class.
     */
    @Override
    public void initialize(URL url, ResourceBundle rb) {
        

        reload();
    }

    @FXML
    private void DenyApp(ActionEvent event) throws SQLException {
        Application O = list.getSelectionModel().getSelectedItem();
        if(O.getState().equals("DENIED"))
        {
            alert1("DENIED APPLICATION","YOU ALREADY DENIED THIS APPLICATION");
            return;
        }
        if(O.getState().equals("ACCEPTED"))
        {
            alert1("ACCEPTED APPLICATION","YOU ALREADY ACCEPTED THIS APPLICATION");
            return;
        }
     


        as.update_application(O.getId(), "DENIED");
        

       
        u=os.getUserByIdOpp(O.getFreelancer().getId());
     

        p1.sendAcceptanceToUser(u.getEmail(), O.getState());
        reload();
        
       

    }

    @FXML
    private void AcceptOpp(ActionEvent event) throws SQLException {
        Application O = list.getSelectionModel().getSelectedItem();
        if(O.getState().equals("DENIED"))
        {
            alert1("DENIED APPLICATION","YOU ALREADY DENIED THIS APPLICATION");
            return;
        }
        if(O.getState().equals("ACCEPTED"))
        {
            alert1("ACCEPTED APPLICATION","YOU ALREADY ACCEPTED THIS APPLICATION");
            return;
        }

        as.update_application(O.getId(), "ACCEPTED");
        reload();
        fos_user u=new fos_user();
        u=os.getUserByIdOpp(O.getFreelancer().getId());
       System.out.println(u.getEmail());

        p1.sendAcceptanceToUser(u.getEmail(), O.getState());
        ContractServiceImpl p=new ContractServiceImpl();
        p.autoGeneratedContract(O.getId());
        
    }

    public void reload() {
        try {
    u = UserSession.getInstance(new fos_user()).getUser();
    
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(HomeOppController.class.getName()).log(Level.SEVERE, null, ex);
        }
        

        data = as.getApplicationsByEntrepriseId(u.getId());
        list.setItems(data);

        list.setCellFactory(OpportunityListView -> new ListOppAppCell());

    }
  

    @FXML
    private void annuler(ActionEvent event) {
        Stage stage = (Stage) CancelButton.getScene().getWindow();
        stage.close();
    }
     private void alert1(String Message,String Accept) {
        Alert a1 = new Alert(Alert.AlertType.ERROR);
        a1.setTitle("Alert");
        a1.setHeaderText(Accept);
        a1.setContentText(Message);
        a1.showAndWait();
    }
    
    

}
